---
- hosts: 172.31.7.192
  become: yes
  tasks:
  - name: execute linux command
    command: hostname -f
    register: myfirsttaskresult

  - name: display my first task result 
    debug:
       msg: "{{myfirsttaskresult}}"
