---
- hosts: 172.31.7.192
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install websever
    dnf:
      name: httpd
      state: present

  - name: start  websever
    service:
      name: httpd
      state: started

  - name: copy text file 
    copy:
      src: mytestfile
      dest: /home/maha/mytestfile

  - name: download internet files
    get_url:
       url: https://adp-mirror-vm1-he-fi.apache.org/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20-deployer.tar.gz
       dest: /home/maha/apache-tomcat-10.0.20-deployer.tar.gz
       force_basic_auth: yes

  - name: copy index file into node side
    template:
        src: myindex.j2
        dest: /var/www/html/index.html
