---
- hosts: mywebserver
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver on RedHat nodes
    dnf:
      name: "{{mywebapackonrehat}}"
      state: present
    when: ansible_os_family=="RedHat"
    

  - name : start webserver on RedHat nodes  
    service: 
      name: "{{mywebapackonrehat}}"
      state: started
    when: ansible_os_family=="RedHat"


      

